language: go

go:
  - 1.10.2

before_install:
  - go get -t -v ./...

install:
  - go install

script:
  - for pkg in $(go list ./...); do go test -coverprofile=coverage-$(echo -n $pkg | tr / _).txt -covermode=atomic $pkg; done
  - cat coverage-*.txt > coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)